apiVersion: v1
kind: Service
metadata:
  name: krm-front
  namespace: meta-namespace
spec:
  selector:
    app: krm-front  # 必须匹配Pod的标签
  ports:
    - protocol: TCP
      port: 80   # 服务暴露端口
      targetPort: 5173  # Pod上的端口