const BASE_URL=import.meta.env.VITE_BASE_URL
export const API_CONFIG={
    loginApi:`${BASE_URL}/auth/login`,
    loginOutApi:`${BASE_URL}/logout`,
    userListApi:`${BASE_URL}/users/list`,
    userDeleteApi:`${BASE_URL}/user/delete`,
    userCreateAPi:`${BASE_URL}/user/add`,
    userUpdateApi:`${BASE_URL}/user/update`,
    //集群相关的api
    clusterListApi:`${BASE_URL}/cluster/list`,
    clusterDeleteApi:`${BASE_URL}/cluster/delete`,
    clusterCreateAPi:`${BASE_URL}/cluster/add`,
    clusterUpdateApi:`${BASE_URL}/cluster/update`,
    clusterGetApi:`${BASE_URL}/cluster/get`,
    //节点相关的api
    nodeListApi:`${BASE_URL}/node/list`,
    nodeGetApi:`${BASE_URL}/node/get`,
    nodeUpdateApi:`${BASE_URL}/node/update`,
    //namespace相关的api
    namespaceListApi:`${BASE_URL}/namespace/list`,
    namespaceCreateApi:`${BASE_URL}/namespace/add`,
    namespaceUpdateApi:`${BASE_URL}/namespace/update`,
    namespaceCopyApi:`${BASE_URL}/namespace/copy`,
    namespaceDeleteApi:`${BASE_URL}/namespace/delete`,
    //pod相关的api
    podListApi:`${BASE_URL}/pod/list`,
    podDeleteApi:`${BASE_URL}/pod/delete`,
    //deployment相关的api
    deploymentListApi:`${BASE_URL}/deployment/list`,
    deploymentGetApi:`${BASE_URL}/deployment/get`,
    deploymentCreateApi:`${BASE_URL}/deployment/add`,
    deploymentUpdateApi:`${BASE_URL}/deployment/update`,
    deploymentDeleteApi:`${BASE_URL}/deployment/delete`,
    //cronjob相关的api
    cronJobListApi:`${BASE_URL}/cronjob/list`,
    cronJobGetApi:`${BASE_URL}/cronjob/get`,
    cronJobCreateApi:`${BASE_URL}/cronjob/add`,
    cronJobUpdateApi:`${BASE_URL}/cronjob/update`,
    cronJobDeleteApi:`${BASE_URL}/cronjob/delete`,
    //daemonset相关的api
    daemonsetListApi:`${BASE_URL}/daemonset/list`,
    daemonsetGetApi:`${BASE_URL}/daemonset/get`,
    daemonsetCreateApi:`${BASE_URL}/daemonset/add`,
    daemonsetUpdateApi:`${BASE_URL}/daemonset/update`,
    daemonsetDeleteApi:`${BASE_URL}/daemonset/delete`,
    //statefulset相关api
    statefulsetListApi:`${BASE_URL}/statefulset/list`,
    statefulsetGetApi:`${BASE_URL}/statefulset/get`,
    statefulsetCreateApi:`${BASE_URL}/statefulset/add`,
    statefulsetUpdateApi:`${BASE_URL}/statefulset/update`,
    statefulsetDeleteApi:`${BASE_URL}/statefulset/delete`,
    //secret相关api
    secretListApi:`${BASE_URL}/secret/list`,
    secretGetApi:`${BASE_URL}/secret/get`,
    secretCreateApi:`${BASE_URL}/secret/add`,
    secretUpdateApi:`${BASE_URL}/secret/update`,
    secretDeleteApi:`${BASE_URL}/secret/delete`,
    //service相关api
    serviceListApi:`${BASE_URL}/service/list`,
    serviceGetApi:`${BASE_URL}/service/get`,
    serviceCreateApi:`${BASE_URL}/service/add`,
    serviceUpdateApi:`${BASE_URL}/service/update`,
    serviceDeleteApi:`${BASE_URL}/service/delete`,
    //ingress相关api
    ingressListApi:`${BASE_URL}/ingress/list`,
    ingressClassListApi:`${BASE_URL}/ingressclass/list`,
    ingressGetApi:`${BASE_URL}/ingress/get`,
    ingressCreateApi:`${BASE_URL}/ingress/add`,
    ingressUpdateApi:`${BASE_URL}/ingress/update`,
    ingressDeleteApi:`${BASE_URL}/ingress/delete`,
    //pvc
    pvcListApi:`${BASE_URL}/persistentvolumeclaim/list`,
    pvcGetApi:`${BASE_URL}/persistentvolumeclaim/get`,
    pvcCreateApi:`${BASE_URL}/persistentvolumeclaim/add`,
    pvcUpdateApi:`${BASE_URL}/persistentvolumeclaim/update`,
    pvcDeleteApi:`${BASE_URL}/persistentvolumeclaim/delete`,
    //pv
    pvListApi:`${BASE_URL}/persistentvolume/list`,
    pvGetApi:`${BASE_URL}/persistentvolume/get`,
    pvCreateApi:`${BASE_URL}/persistentvolume/add`,
    pvUpdateApi:`${BASE_URL}/persistentvolume/update`,
    pvDeleteApi:`${BASE_URL}/persistentvolume/delete`,
    //configmap
    configMapListApi:`${BASE_URL}/configmap/list`,
    configMapGetApi:`${BASE_URL}/configmap/get`,
    configMapCreateApi:`${BASE_URL}/configmap/add`,
    configMapUpdateApi:`${BASE_URL}/configmap/update`,
    configMapDeleteApi:`${BASE_URL}/configmap/delete`,
    //tools
    yamlCreateOrUpdate:`${BASE_URL}/yaml/create`,
}
export const TOKEN_CONFIG={
    "TOKEN_NAME":"Authorization"

}
